name: hexentials
recipe: drupal8
config:
  webroot: docroot/web
  php: 7.4
  config:
    php: config/php.ini
  # drush: 10

proxy:
  appserver:
    - hexentials.lndo.site
  search:
    - solr.hexentials.lndo.site:8983
  mailhog:
    - mailhog.hexentials.lndo.site

services:
  appserver:
    build:
      - cd docroot && composer install
    build_as_root:
      # PHP extension needed to improve the JS minify process.
      - pecl install jsmin

  database:
    type: mariadb:10.4
    portforward: true

  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

  search:
    type: solr:8
    portforward: true
    core: hex
    config:
      dir: docroot/solr-config

  cache:
    type: redis
    portforward: true
