<?php

/**
 * @file
 * Functions to support theming in the hex_commerce theme.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter for blocks.
 */
function hex_commerce_theme_suggestions_block_alter(&$suggestions, $variables) {

  // Load theme suggestions for blocks from parent theme.
  foreach ($suggestions as &$suggestion) {
    $suggestion = str_replace('hex_commerce_', 'flexi_cart_', $suggestion);
  }
}
